language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jsinit' ]; then cd .. && eval "mv $currentfolder generator-jsinit" && cd generator-jsinit; fi
